package hangman;

/**
 *
 * @author reprise
 */
public class gameform extends javax.swing.JFrame {

    /**
     * Creates new form game form
     */
    public gameform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hangScreenPanel = new javax.swing.JPanel();
        hangScreen = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Cbutton = new javax.swing.JButton();
        Bbutton = new javax.swing.JButton();
        Dbutton = new javax.swing.JButton();
        DifficultyLabel = new javax.swing.JLabel();
        DifficultyCombobox = new javax.swing.JComboBox();
        startGameButton = new javax.swing.JButton();
        Ebutton = new javax.swing.JButton();
        Fbutton = new javax.swing.JButton();
        Gbuton = new javax.swing.JButton();
        Ibutton = new javax.swing.JButton();
        Hbutton = new javax.swing.JButton();
        Jbuton = new javax.swing.JButton();
        Dbutton8 = new javax.swing.JButton();
        Dbutton9 = new javax.swing.JButton();
        Dbutton10 = new javax.swing.JButton();
        Dbutton11 = new javax.swing.JButton();
        Dbutton12 = new javax.swing.JButton();
        Lbutton = new javax.swing.JButton();
        Cbutton1 = new javax.swing.JButton();
        Dbutton13 = new javax.swing.JButton();
        triesLeftCountLabel = new javax.swing.JLabel();
        triesLeftScreen = new javax.swing.JTextField();
        Kbutton = new javax.swing.JButton();
        guesserScreen1 = new javax.swing.JTextField();
        Abutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hangman");
        setResizable(false);

        hangScreenPanel.setLayout(null);

        hangScreen.setIcon(new javax.swing.ImageIcon("/home/reprise/Dropbox/Programming/01 Java/Hangman/hangImg/post.png")); // NOI18N
        hangScreen.setAutoscrolls(true);
        hangScreen.setFocusable(false);
        hangScreenPanel.add(hangScreen);
        hangScreen.setBounds(10, -20, 270, 310);
        hangScreen.getAccessibleContext().setAccessibleName("IMAGE");

        Cbutton.setText("C");
        Cbutton.setToolTipText("");

        Bbutton.setText("B");
        Bbutton.setToolTipText("");

        Dbutton.setText("D");
        Dbutton.setToolTipText("");

        DifficultyLabel.setText("Difficulty:");

        DifficultyCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Easy", "Medium", "Hard" }));

        startGameButton.setText("START GAME");
        startGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameButtonActionPerformed(evt);
            }
        });

        Ebutton.setText("E");
        Ebutton.setToolTipText("");

        Fbutton.setText("F");
        Fbutton.setToolTipText("");

        Gbuton.setText("G");
        Gbuton.setToolTipText("");

        Ibutton.setText("I");
        Ibutton.setToolTipText("");

        Hbutton.setText("H");
        Hbutton.setToolTipText("");

        Jbuton.setText("J");
        Jbuton.setToolTipText("");

        Dbutton8.setText("D");
        Dbutton8.setToolTipText("");

        Dbutton9.setText("D");
        Dbutton9.setToolTipText("");

        Dbutton10.setText("D");
        Dbutton10.setToolTipText("");

        Dbutton11.setText("D");
        Dbutton11.setToolTipText("");

        Dbutton12.setText("D");
        Dbutton12.setToolTipText("");

        Lbutton.setText("L");
        Lbutton.setToolTipText("");

        Cbutton1.setText("C");
        Cbutton1.setToolTipText("");

        Dbutton13.setText("D");
        Dbutton13.setToolTipText("");

        triesLeftCountLabel.setText("Tries Left:");

        triesLeftScreen.setEditable(false);
        triesLeftScreen.setFont(new java.awt.Font("Digital Readout Thick Upright", 0, 24)); // NOI18N
        triesLeftScreen.setFocusable(false);

        Kbutton.setText("K");
        Kbutton.setToolTipText("");

        guesserScreen1.setEditable(false);
        guesserScreen1.setBackground(new java.awt.Color(153, 255, 255));
        guesserScreen1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        guesserScreen1.setToolTipText("This is the word you need to guess.");
        guesserScreen1.setFocusable(false);
        guesserScreen1.setName(""); // NOI18N
        guesserScreen1.setRequestFocusEnabled(false);

        Abutton.setText("A");
        Abutton.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hangScreenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(triesLeftCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(triesLeftScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DifficultyLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DifficultyCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(startGameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(guesserScreen1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(Abutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Ebutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Fbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Gbuton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Hbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Ibutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Jbuton)))
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(Kbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cbutton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dbutton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dbutton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dbutton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dbutton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dbutton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dbutton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hangScreenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DifficultyLabel)
                            .addComponent(DifficultyCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(triesLeftCountLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startGameButton)
                            .addComponent(triesLeftScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guesserScreen1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cbutton)
                    .addComponent(Bbutton)
                    .addComponent(Dbutton)
                    .addComponent(Ebutton)
                    .addComponent(Fbutton)
                    .addComponent(Gbuton)
                    .addComponent(Hbutton)
                    .addComponent(Ibutton)
                    .addComponent(Jbuton)
                    .addComponent(Abutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cbutton1)
                    .addComponent(Lbutton)
                    .addComponent(Dbutton13)
                    .addComponent(Dbutton12)
                    .addComponent(Dbutton10)
                    .addComponent(Dbutton11)
                    .addComponent(Dbutton9)
                    .addComponent(Dbutton8)
                    .addComponent(Kbutton))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        DifficultyLabel.getAccessibleContext().setAccessibleName("DifficultyLabel");
        triesLeftCountLabel.getAccessibleContext().setAccessibleName(":");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //START GAME BUTTON!!!!======================================================================================================================
    private void startGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameButtonActionPerformed
        WordShuffle game = new WordShuffle();
        hangScreen.setIcon(new javax.swing.ImageIcon("/home/reprise/Dropbox/Programming/01 Java/Hangman/hangImg/post.png")); 
        triesLeftScreen.setText("6");
        
        difficulty = DifficultyCombobox.getSelectedIndex();
        System.out.println("difficulty index: " + difficulty );
        //index 0 is easy, index 1 is medium, index 2 is hard.
        
        
        if (difficulty == 0){
            //easy game started
            wordToGuess = game.doWordBag1();
            System.out.println("Word: " + wordToGuess);
           
            //Draw the underdashes:
            StringBuilder stringBuilder = new StringBuilder();
            wordToGuessLength = wordToGuess.length();
            System.out.println("WordLength:" + wordToGuessLength);

            for (int i = 0; i < wordToGuessLength; i++){
                stringBuilder.append("_ ");
                underscores = stringBuilder.toString();
            }
            System.out.println("underscores" + underscores);
            guesserScreen1.setText(underscores);
            guesserScreen1.setToolTipText("The word you need to guess has " + wordToGuessLength + " letters.");
        }
        
        else if (difficulty == 1){
            //medium game started
            wordToGuess = game.doWordBag2();
            System.out.println("Word: " + wordToGuess);
            
            //Draw the underdashes:
            StringBuilder stringBuilder = new StringBuilder();
            wordToGuessLength = wordToGuess.length();
            System.out.println("WordLength:" + wordToGuessLength);

            for (int i = 0; i < wordToGuessLength; i++){
                stringBuilder.append("_ ");
                underscores = stringBuilder.toString();
            }
            System.out.println("underscores:" + underscores);
            guesserScreen1.setText(underscores);
            guesserScreen1.setToolTipText("The word you need to guess has " + wordToGuessLength + " letters.");

        }
        
        else if (difficulty == 2){
            //hard game started
            wordToGuess = game.doWordBag3();
            System.out.println("Word: " + wordToGuess);
            
            //Draw the underdashes:
            StringBuilder stringBuilder = new StringBuilder();
            wordToGuessLength = wordToGuess.length();
            System.out.println("WordLength:" + wordToGuessLength);

            for (int i = 0; i < wordToGuessLength; i++){
                stringBuilder.append("_ ");
                underscores = stringBuilder.toString();
            }
            System.out.println("underscores" + underscores);
            guesserScreen1.setText(underscores);
            guesserScreen1.setToolTipText("The word you need to guess has " + wordToGuessLength + " letters.");
        }   
    }//GEN-LAST:event_startGameButtonActionPerformed

    public static void main(String args[]) {
         
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameform().setVisible(true);
            }
        });
    }
    
    //If letter wrong, change the Hangman screen with this code:
    // hangScreen.setIcon(new javax.swing.ImageIcon("/home/reprise/Dropbox/Programming/01 Java/Hangman/hangImg/post.png"));
    //find out how to make it by local directory.
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Abutton;
    private javax.swing.JButton Bbutton;
    private javax.swing.JButton Cbutton;
    private javax.swing.JButton Cbutton1;
    private javax.swing.JButton Dbutton;
    private javax.swing.JButton Dbutton10;
    private javax.swing.JButton Dbutton11;
    private javax.swing.JButton Dbutton12;
    private javax.swing.JButton Dbutton13;
    private javax.swing.JButton Dbutton8;
    private javax.swing.JButton Dbutton9;
    private javax.swing.JComboBox DifficultyCombobox;
    private javax.swing.JLabel DifficultyLabel;
    private javax.swing.JButton Ebutton;
    private javax.swing.JButton Fbutton;
    private javax.swing.JButton Gbuton;
    private javax.swing.JButton Hbutton;
    private javax.swing.JButton Ibutton;
    private javax.swing.JButton Jbuton;
    private javax.swing.JButton Kbutton;
    private javax.swing.JButton Lbutton;
    private javax.swing.JTextField guesserScreen1;
    private javax.swing.JLabel hangScreen;
    private javax.swing.JPanel hangScreenPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton startGameButton;
    private javax.swing.JLabel triesLeftCountLabel;
    private javax.swing.JTextField triesLeftScreen;
    // End of variables declaration//GEN-END:variables

//GLOBAL VARIABLES:
int difficulty = 0;
String wordToGuess = "";
String underscores = "";
int wordToGuessLength = 0;
int chancesLeftCounter = 6;

}



